name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Gyoumi 
          template: classic

          base: header, repositories
          config_timezone: Australia/Sydney

          plugin_languages: yes
          plugin_languages_ignored: >-
                      html, css, md
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          commits_authoring: Gyoumi, gyoumi@users.noreply.github.com

          plugin_leetcode: yes
          plugin_leetcode_user: gyumi

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          filename: github-metrics.svg
        
          committer_branch: master
          committer_message: "chore: update metrics"
